import java.util.*;
//generated by ChatGPT, with some modifications by me
public class MazeGenerator {
    static int rows = 80;
    static int cols = 80;
    static char[][] maze = new char[rows][cols];
    static Random rand = new Random();

    public static void main(String[] args) {
        // Initialize all walls
        for (int r = 0; r < rows; r++)
            Arrays.fill(maze[r], '@');

        // Carve a guaranteed path from W to $
        int r = 0, c = 0;
        maze[r][c] = 'W';
        while (r < rows - 1 || c < cols - 1) {
            int dr = 0, dc = 0;
            if (r < rows - 1 && c < cols - 1) {
                if (rand.nextBoolean()) dr = 1; else dc = 1;
            } else if (r < rows - 1) dr = 1;
            else dc = 1;

            r += dr; c += dc;
            maze[r][c] = '.';
        }
        maze[rows-1][cols-1] = '$';

        // Randomly open some walls for branches
        for (int i = 0; i < rows * cols / 3; i++) {
            int rr = rand.nextInt(rows);
            int cc = rand.nextInt(cols);
            if (maze[rr][cc] == '@') maze[rr][cc] = '.';
        }

        // Print maze
        System.out.println(rows + " " + cols + " 1");
        for (int x = 0; x < rows; x++) {
            System.out.println(new String(maze[x]));
        }
    }
}